### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by umekzg** [TalalMash/SmoothWAN#16]
Hi!

Neat piece of software!

As i have a dedicated server i also have option for port forwarding.

I'm aware that it would be double NAT but is it possible to fwd a port to LAN device from speedify in current build?

Also are USB 4G modems supported?

Thx!

**Comment by umekzg** [comment]
scrap this... i didn't see discussions.....

**Comment by TalalMash** [comment]
I've added VPN port forward quick configuration page a while ago, its not in the Wiki yet as I don't have a dedicated plan to test, please let me know if it works
![image](https://user-images.githubusercontent.com/96490382/159164510-4138a37c-9af8-489a-a9cb-a9b0ce7c01de.png)
![image](https://user-images.githubusercontent.com/96490382/159164513-a5220afa-e6d5-4568-9571-1fdc6f7c2ce4.png)

With regarding USB modems, I'll update README and replace the word "cellular" with "4G" as it seems to be confusing. 
RNDIS/USB-ethernet-like modems are supported by Plug and Play function and the Multi-WAN configration pages (including renaming) 
QMI and NCM can be set up manually in "Interfaces" page only as they're uncommon and require specific settings from ISP.

**Comment by umekzg** [comment]
Wow nice!
Testing tomorrow!

**Comment by TalalMash** [comment]
Thanks!

**Comment by umekzg** [comment]
Can you make a bcm2710 build? I don't have any rpi4 laying around.

**Comment by TalalMash** [comment]
> Can you make a bcm2710 build? I don't have any rpi4 laying around.

I don't have any older rpi as they're very slow, the speed matters for latency and bufferbloat, not just bandwidth. I'll build one soon for experimenting but without multi WAN USB renaming UI. Plug and play is still supported.

**Comment by TalalMash** [comment]
> Can you make a bcm2710 build? I don't have any rpi4 laying around.
Added in latest release. Wi-Fi may need additional configuration, use ethernet.
Set interfaces manually in "Interfaces" page, the Multi-WAN USB app is not functional as I don't have the hardware to test.

**Comment by TalalMash** [comment]
> Can you make a bcm2710 build? I don't have any rpi4 laying around.

Any updates regarding the RPi3 build?

**Comment by umekzg** [comment]
Actually i was in covid for 10 days...
I'm now catching up on everything...

When i do test i will post results here.

**Comment by TalalMash** [comment]
> Actually i was in covid for 10 days... I'm now catching up on everything...
> 
> When i do test i will post results here.

Wow thats unfortunate, hope for a speedy recovery!

**Comment by umekzg** [comment]
I managed to source rpi4 and tried the port fwd. Didn't work.

**Comment by TalalMash** [comment]
Thank you for reporting.
