### ISSUE TITLE
Change LAN IP

### ISSUE THREAD

**Issue by neosaadmin** [TalalMash/SmoothWAN#22]
Changing LAN IP results in the old IP 172.17.17.2 still being active and showing speedify not able to load on the overview when viewing at say 192.168.3.1, but speedify is running and active at 172.17.17.2 still.

**Comment by TalalMash** [comment]
Hello, good issue, changing IP requires a post changing script that is being worked on, the current workaround is using a unique IP such as the default. Few components should be run as services for clean restarts (e.g firewall rules, tailscale, LXC containers such as Pi-hole).
Will be added in 0.99.6

**Comment by TalalMash** [comment]
> Changing LAN IP results in the old IP 172.17.17.2 still being active and showing speedify not able to load on the overview when viewing at say 192.168.3.1, but speedify is running and active at 172.17.17.2 still.

In the meantime you can simply change the IP in Firewall -> Custom Rules

**Comment by TalalMash** [comment]
Temporary till next version:
In Web UI Terminal app, login and type:
`wget https://raw.githubusercontent.com/TalalMash/SmoothWAN-web/main/switchto192.sh`
`cat switch192.sh` (check content)
`sh switch192.sh` 
To revert replace 192 with 172 in URL.

**Comment by TalalMash** [comment]
Fixed in latest release, reboot after changing IP.
Re-open if there are issues.
Thanks.
