### ISSUE TITLE
Raspi 4 v0.99.6 disconnect every 30 mins or so 

### ISSUE THREAD

**Issue by hle5128** [TalalMash/SmoothWAN#36]
Hi,
I left speedify run overnight, and I notice it gets auto disconnected or so on every 30 mins or close to it.
I have two modem 5G hooks up to it, and they are online just fine; the reason I know is I set the speed test on my nas every 30 mins throughout the day, and when speedify auto disconnects, the speed test is still run from one of the two interfaces.

Here are the logs I got in the morning; I turned them on and 30 mins later disconnected again.

[REDACTED - irrelevant]

**Comment by TalalMash** [comment]
Try to connect to "Torrent friendly server" to see if Speedify is disconnecting due to P2P traffic.

**Comment by TalalMash** [comment]
To generate Speedify logs, do tar -zcvf /www/spdlog.tar.gz /usr/share/speedify/logs/
Visit http://172.17.17.2/spdlog.tar.gz to download and upload it here.

**Comment by hle5128** [comment]
[spdlog.tar.gz](https://github.com/TalalMash/SmoothWAN/files/8695369/spdlog.tar.gz)

here is it

**Comment by TalalMash** [comment]
![image](https://user-images.githubusercontent.com/96490382/168483102-ca3d68fc-8152-4609-b51c-2a04f4491fec.png)
Torrenting is detected.
You can either use a torrenting server, or another country that has the ability to block torrents as opposed to servers that disconnect, I'm not aware on how to segregate these.
You can also use VPN on top of VPN, it's preferred to set Speedify transport mode to UDP mode and use a UDP VPN.

**Comment by hle5128** [comment]
probably I'm going to run the wireguard client on the nas server.
been testing alot lately with smoothwan, and one thing i notice, combining too wans do make speed slower.
For example, each wan individual when i test up to 200 to 300 Mbps but when run through smoothwan, i only get around 150ish max on both, regardless which mode i select or protocol.
I might just be running this through the flint instead just 1 wan and run wireguard client on it. Instead of doing speedify

**Comment by TalalMash** [comment]
I included the speeds in the README page for each device, 200-300 each is way too high for a Pi4 to handle, try disabling encryption although the difference will be minimal. The flint will be much slower and the R4S slightly faster. 
x86 hardware may be the only option e.g Intel J3060 Mini PC (~$150+).

**Comment by TalalMash** [comment]
You can also discuss the performance for the NanoPi R4S in it's issue page, you can overclock to 2GHz (safe max) to check, there is one testing report left regarding AES hardware acceleration.

**Comment by hle5128** [comment]
What about r4s? 
I might het the intel j3060 mini pc to test today.

**Comment by hle5128** [comment]
Yes, i coundnt get it online. I posted in it issues, can you take a look. Want to test AES for you since all my 3 wans combined over 1G

**Comment by TalalMash** [comment]
> Intel J3060

To be on the safe side, I'd recommend something with more power than this baseline family, try to avoid Braswell series.

**Comment by TalalMash** [comment]
> What about r4s? I might het the intel j3060 mini pc to test today.
> […](#)
> On May 15, 2022, at 12:46 PM, Talal ***@***.***> wrote: ﻿ I included the speeds in the README page for each device, 200-300 each is way too high for a Pi4 to handle, try disabling encryption although the difference will be minimal. The flint will be much slower and the R4S slightly faster. x86 hardware may be the only option e.g Intel J3060 Mini PC (~$150+). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

To be on the safe side, I'd recommend something with more power than this baseline family, try to avoid Braswell series.
An i3 based Qotom should do well, includes multiple NICs as a bonus.
