### ISSUE TITLE
Slate AX Custom Bypasses Failed

### ISSUE THREAD

**Issue by hle5128** [TalalMash/SmoothWAN#54]
I recorded a video here:

https://share.getcloudapp.com/DOudpyr8

Also, click download log, and config fails.
<img width="937" alt="Screen Shot 2022-08-09 at 9 27 05 PM" src="https://user-images.githubusercontent.com/8794968/183790364-390708c6-bf53-430c-af1b-b256c3eaf62d.png">

**Comment by TalalMash** [comment]
I didn't update the app with the current nginx root level, it's different from the Pi, after clicking the button, visit 172.17.17.2/spdlogs.tar.gz
Ill release a hot fix soon.

**Comment by TalalMash** [comment]
Regarding the bypass app, I don't have access to my Mac, does it work with Chrome/FF?

**Comment by TalalMash** [comment]
Fixed with HR1 release, reopen if the issue persists.
Thanks for the report.
