### ISSUE TITLE
Error while build.sh - Cannot install package libwolfssl4.8.1.66253b90

### ISSUE THREAD

**Issue by MarshmallowB** [TalalMash/SmoothWAN#9]
Hey,
while i run "sh build.sh" i get this error
"
 opkg_install_cmd: Cannot install package libwolfssl4.8.1.66253b90.
"
and this
"
make[2]: *** [Makefile:167: package_install] Error 255
make[1]: *** [Makefile:122: _call_image] Error 2
make: *** [Makefile:240: image] Error 2
"
i hope someone can help me. <3

edit:
i changed libwolfssl4.8.1.66253b90 to libwolfssl5.1.1.99a5b54a 
now it works! <3 
thank you for your work

**Comment by TalalMash** [comment]
Hello, try the latest commit, you can remove the versioning from libwolfssl4 for latest which is what the build uses.
